# Generated by Django 4.2.1 on 2023-05-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_band_bike_rename_name_bike_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='colors',
            field=models.CharField(default='white', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='mark',
            field=models.CharField(default='maiwenn', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='state',
            field=models.CharField(default='good', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bike',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
