# Generated by Django 4.2.1 on 2023-05-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_bike_colors_bike_mark_bike_state_alter_bike_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='mark',
            new_name='brand',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='security',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='state',
        ),
        migrations.AddField(
            model_name='bike',
            name='color',
            field=models.CharField(default='black', max_length=30),
            preserve_default=False,
        ),
    ]
