# Generated by Django 4.2.1 on 2023-05-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_mark_bike_brand_remove_bike_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bike',
            name='state',
            field=models.CharField(choices=[('G', 'Good'), ('VG', 'Very Good'), ('P', 'Perfect'), ('N', 'New'), ('B', 'Bad')], default='N', max_length=5),
            preserve_default=False,
        ),
    ]
